@startuml
class Balle {
  - couleur
  + onStepTime()
  + getCouleur()
}
class Couleur {
  - random
  - rouge
  - vert
  - bleu
  + getRouge()
  + setRouge()
  + getVert()
  + setVert()
  + getBleu()
  + setBleu()
  + setRandom()
}
class LeMonde {
  - min_x
  - max_x
  - min_y
  - max_y
  - maitreDesActions
  - vue
  - robot
  - balles
  - r
  - robot_reach
  + aleatoire()
  + creeBalle()
  + creeAleatoireBalles()
  + faireUnPasDansLeTemps()
  + getBalles()
  + getRobot()
  + getVue2D()
  + getMaitreDesActions()
  + faireLesActions()
  + wrapObjetStatique()
}
class MaitreDesActions {
  - mouvement
  - faireAttraperOuRelacherLaBalle
  + reset()
  + faireBouger()
  + faireBouger()
  + stopBouger()
  + getMouvementX()
  + getMouvementY()
  + ilFautAttraperOuRelacherLaBalle()
  + faireAttraperOuRelacherLaBalle()
  + onAttrapeOuRelacherLaBalle()
}
class ObjetDynamique {
  - mass
  - velocity
  - netForce
  + setMass()
  + addForce()
  + addForce()
  + timeStep()
  + getVelocity()
  + onStepTime()
}
class ObjetStatique {
  - position
  + getX()
  + getY()
  + setX()
  + setY()
  + setPosition()
  + deplacer()
  + mesureDistance()
}
class Robot {
  - balles
  - speed
  - acceleration
  - motion
  + bouger()
  + onStepTime()
  + jaiUneBalle()
  + attraperUneBalle()
  + relacherLaBalle()
  + siTransporte()
  + nbBalles()
}
class Vecteur2D {
  - x
  - y
  + getX()
  + getY()
  + setX()
  + setY()
  + set()
  + set()
  + add()
  + add()
  + addScalar()
  + sub()
  + subScalar()
  + zero()
  + mult()
  + distance()
}
class ArrayList {
}
class Random {
}
class Vue2D {
  - zoom
  + getX()
  + getY()
  + scale()
}
class App {
  - WIDTH
  - HEIGHT
  - canvas
  - clavier
  - animationTimer
  - leMondeFX
  + start()
  + handleKeyPress()
  + handleKeyReleased()
  + update()
  + draw()
  + main()
}
class BalleFX {
  - balle
  - porteBalle
  - color
  + getBalle()
  + setPorteBalle()
  + draw()
}
class ClavierPermanent {
  - touches_actifs
  + setTouche()
  + touchePressed()
  + toucheReleased()
  + getTouche()
}
class LeMondeFX {
  - leMonde
  - robotFX
  - ballesFX
  + getLeMonde()
  + getNBBalle()
  + draw()
}
class ObjetDessin {
  - vue2d
  - vueFinal
  - gc
  + draw()
}
class RobotFX {
  - robot
  - nbBalle
  + getNBBalle()
  + draw()
}
class SystemInfo {
  + javaVersion()
  + javafxVersion()
}
class VueFinal {
  - width
  - height
  + setWidth()
  + setHeight()
  + getWidth()
  + getHeight()
  + vueX()
  + vueY()
}
Balle -- Couleur
Couleur -- Random
Couleur *-- Random
LeMonde -- MaitreDesActions
LeMonde -- Vue2D
LeMonde -- Robot
LeMonde -- ArrayList
LeMonde -- Random
LeMonde ..> Balle
LeMonde ..> robot
LeMonde ..> 
MaitreDesActions -- Vecteur2D
ObjetDynamique -- Vecteur2D
ObjetDynamique ..> 
ObjetStatique -- Vecteur2D
Robot -- ArrayList
Robot -- Vecteur2D
App -- ClavierPermanent
App -- LeMondeFX
App ..> StackPane
App ..> Scene
App ..> scene
App ..> stage
App ..> animationTimer
App ..> gc
App ..> leMondeFX
App ..> 
BalleFX -- Balle
BalleFX ..> gc
LeMondeFX -- LeMonde
LeMondeFX -- RobotFX
LeMondeFX -- ArrayList
ObjetDessin -- Vue2D
ObjetDessin -- VueFinal
RobotFX -- Robot
RobotFX ..> gc
RobotFX ..> nbBalle
@enduml